#include "pqshelp.h"

PQS_EXPORT_API const char* pqs_help_client_detail(void)
{
	return
		"***PQS CLIENT SETUP AND OPERATIONS***\n"
		"\n"
		"**Purpose**\n"
		"The PQS client connects to a PQS server over the QSMS encrypted transport.\n"
		"After the encrypted channel is established, the client authenticates with\n"
		"a PQS username and passphrase. The authenticated session can execute\n"
		"permitted commands and use the PQS encrypted file-transfer subsystem.\n"
		"\n"
		"**Initial setup**\n"
		"1. Obtain the server public key from the server administrator.\n"
		"2. Verify the server public-key fingerprint out-of-band.\n"
		"3. Start the client and enter the server address, public-key path,\n"
		"   username, and passphrase when prompted.\n"
		"4. On first contact with a server, review the displayed SHA3-256\n"
		"   fingerprint before saving the known-hosts entry.\n"
		"\n"
		"**Host trust commands**\n"
		"*key, fp, fingerprint -Display the loaded server public key and SHA3-256 fingerprint.\n"
		"*known, khlist -Display the client known-hosts database.\n"
		"*khremove [host] -Remove a pinned known-hosts entry.\n"
		"\n"
		"**Remote command execution**\n"
		"Any input that is not a client control command is sent as a remote\n"
		"command request. The server authorizes the request using the authenticated\n"
		"user's privilege level, command policy, and assigned shell profile.\n"
		"\n"
		"**File-transfer commands**\n"
		"get [remote-path] [local-path] -Download one remote file.\n"
		"get -r [remote-directory] [local-directory] -Recursively download a remote directory.\n"
		"put [local-path] [remote-path] -Upload one local file.\n"
		"put -r [local-directory] [remote-directory] -Recursively upload a local directory.\n"
		"list [remote-path] -List a remote directory.\n"
		"mkdir [remote-path] -Create a remote directory.\n"
		"remove [remote-path] -Remove a remote file.\n"
		"\n"
		"**File-transfer security**\n"
		"Transfers are carried inside the authenticated QSMS/PQS channel. The\n"
		"server confines remote paths under the authenticated user's transfer root.\n"
		"Absolute paths, drive-letter paths, parent traversal, and symbolic-link\n"
		"escapes are rejected. File transfers include SHA3-256 metadata and progress reporting.\n"
		"\n"
		"**Session commands**\n"
		"help -Display the short client command help.\n"
		"detail -Display this detailed setup and operations guide.\n"
		"quit -Close the PQS session and exit the client.\n"
		"\n"
		"**Configuration**\n"
		"The client uses pqs.conf for persistent defaults such as application path,\n"
		"server public-key path, known-hosts path, log path, target host, target\n"
		"port, default username, log level, and strict host-key checking.\n"
		"\n";
}

PQS_EXPORT_API const char* pqs_help_server_detail(void)
{
	return
		"PQS SERVER SETUP AND OPERATIONS\n"
		"\n"
		"***Purpose***\n"
		"The PQS server provides a post-quantum secure remote command and file\n"
		"transfer service over QSMS. The server authenticates users through the\n"
		"PQS user database, applies privilege and command policy, selects an\n"
		"authorized shell profile, and records security-relevant events in the\n"
		"structured audit log.\n"
		"\n"
		"**Initial setup**\n"
		"1. Start the server once to create the application directory, configuration\n"
		"   file, server key material, user database, shell database, policy database, and log file.\n"
		"2. Run the key or fingerprint command and distribute the server public key\n"
		"   and SHA3-256 fingerprint to clients through an authenticated channel.\n"
		"3. Enter user mode and create at least one administrative user.\n"
		"4. Review shell profiles and command policies before allowing remote shell  access.\n"
		"\n"
		"Root server commands\n"
		"user -Enter user administration mode.\n"
		"shell -Enter shell profile administration mode.\n"
		"policy -Enter command policy administration mode.\n"
		"key -Display the encoded server public key and fingerprint.\n"
		"fp, fingerprint -Display the server public-key fingerprint.\n"
		"keyscan -Display a known-hosts-compatible host|fingerprint line.\n"
		"sandbox -Display command sandbox status.\n"
		"help -Display the short server command help.\n"
		"detail -Display this detailed setup and operations guide.\n"
		"quit -Stop the PQS server.\n"
		"\n"
		"**User mode commands**\n"
		"add [username] [guest|user|admin] -Create a user and print a generated passphrase once.\n"
		"remove [username] -Remove a user record.\n"
		"enable [username] / disable [username] -Enable or disable a user account.\n"
		"passwd [username] -Generate a new user passphrase and update the SCB verifier.\n"
		"privilege [username] [guest|user|admin] -Change a user's privilege level.\n"
		"show [username] -Display a user record without secret material.\n"
		"list -List configured users.\n"
		"exit -Return to server mode.\n"
		"\n"
		"**Shell mode commands**\n"
		"list -List configured shell profiles.\n"
		"add [name] [type] [path] -Add a shell profile. Common types include cmd, powershell, pwsh, sh, bash, zsh, and custom.\n"
		"remove [name] -Remove a shell profile.\n"
		"enable [name] / disable [name] -Enable or disable a shell profile.\n"
		"default [name] -Set the default shell profile.\n"
		"assign [username] [name] -Assign a shell profile to a user.\n"
		"allow [guest|user|admin] [name] / deny [guest|user|admin] [name] -Update the privilege mask for a shell profile.\n"
		"show [name] -Display a shell profile.\n"
		"exit -Return to server mode.\n"
		"\n"
		"**Policy mode commands** \n"
		"list -List command policies.\n"
		"add [name] [no-shell|restricted|forced|raw-shell] -Add a command policy.\n"
		"remove [name] -Remove a command policy.\n"
		"enable [name] / disable [name] -Enable or disable a policy.\n"
		"mode [name] [no-shell|restricted|forced|raw-shell] -Change a policy enforcement mode.\n"
		"allow [name] [command] / deny [name] [command] -Add a command verb to a policy allow-list or deny-list.\n"
		"unallow [name] [command] / undeny [name] [command] -Remove a command verb from a policy allow-list or deny-list.\n"
		"force [name] [command] -Set the forced command for a forced-command policy.\n"
		"assign [guest|user|admin] [name] -Assign a policy to a privilege level.\n"
		"show [name] -Display a policy record.\n"
		"exit -Return to server mode.\n"
		"\n"
		"**Authentication and authorization**\n"
		"Users authenticate with a username and passphrase over the encrypted QSMS\n"
		"channel. The server stores only SCB verifier material and never stores the\n"
		"plaintext passphrase. After login, command execution is authorized by the\n"
		"user's privilege, assigned command policy, and permitted shell profile.\n"
		"\n"
		"File-transfer operations\n"
		"The server supports get, put, list, mkdir, remove, recursive upload, and\n"
		"recursive download over the encrypted PQS channel. Remote file paths are\n"
		"confined under a per-user transfer root. File metadata includes SHA3-256\n"
		"hashes, and symbolic-link or traversal escapes are rejected.\n"
		"\n"
		"Configuration and logs\n"
		"The server uses pqsd.conf for paths, logging, sandbox settings, timeouts,\n"
		"and operational limits. User, shell, and policy records are stored in\n"
		"separate server database files. Logs record operational and audit events\n"
		"without writing passphrases, verifiers, private keys, session keys, nonces,\n"
		"transcript hashes, or command output.\n"
		"\n";
}
